### ISSUE TITLE
possible autoformat improvement

### ISSUE THREAD

**Issue by kloimhardt** [oakes/tag-soup#2]
In the Nightlight editor, if in the following code I press [Return] in front of "1"
```
((partial + 2) 1)
```
I will get the unexpected result
```
((partial + 2 
  1))
```
If in tag-soup.core I changed line 42 from
```
(vector? first-val)
```
to
```
(or (vector? first-val) (list? first-val))
```
I would get the expected result
```
((partial + 2) 
 1)
```

**Comment by oakes** [comment]
Good idea; I added your suggestion and it should make its way to nightlight et al pretty soon. Feel free to send these suggestions as PRs in the future if you'd like. I appreciate it, thanks!
